homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.5155
  longitude: 13.4062
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 32
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Example configuration.yaml entry
# device_tracker:
#   - platform: nmap_tracker
#     hosts: 192.168.1.1/24

# Example configuration.yaml entry
# device_tracker:
#   - platform: cisco_ios
#     host: 192.168.1.1
#     username: !secret YOUR_ADMIN_USERNAME
#     password: !secret YOUR_ADMIN_PASSWORD

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

enocean:
  device: /dev/ttyUSB0

binary_sensor:
  - platform: enocean
    name: "button sensor"
    id: [0xFE,0xFB,0xFE,0x61]
  # - platform: enocean
  #   name: "no-button sensor"
  #   id: [0xE2,0x15,0x00,0x00,0x1E,0xE7]

# sensor:
#   - name: Television
#     platform: enocean
#     id: [0xFE,0xFB,0xFE,0x61]

# Text to speech
tts:
  platform: google

# Example configuration.yaml entry
#arduino:
#  port: /dev/ttyACM0

# Example configuration.yaml entry
#switch:
#  platform: arduino
#  pins:
#    13:
#      name: Light Desk
#      initial: false 
#      negate: false 


light:
  - platform: dali
#    - platform: lifx
#      #server: 192.168.1.10
#      name: "ciao"
     #server: 192.168.1.10

# Example configuration.yaml entry
# device_tracker:
#  - platform: bluetooth_le_tracker
#    discovery: enabled
#    track_new_devices: True
#    consider_home: 180
#    interval_seconds: 5

notify:
  - name: slack
    username: HomeAssistant
    platform: slack
    api_key: !secret slackapikey
    default_channel: '@riccardo'
    icon: ":house_with_garden:"

switch:
  - platform: gog 
  # - platform: dali
  # - platform: enocean
  #   id: [0xFE,0xFB,0xFE,0x61]

# automation:
# - alias: 'Morning Alignment Gong'
#   trigger:
#     platform: time
#     # When 'after' is used, you cannot also match on hour, minute, seconds.
#     # Military time format.
#     after: '10:00:00'
#   action:
#     - service: switch.turn_on

# switch:
#   platform: dali 

automation:
- alias: '10.00 Daily Alignment Gong'
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    after: '10:00:00'
  condition:
  - condition: time
    weekday:
      - tue
      - wed
      - thu
      - fri
  action:
    - service: switch.turn_on
      entity_id: switch.gong
- alias: '9.00 Monday Alignment Gong'
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    after: '9:00:00'
  condition:
  - condition: time
    weekday:
      - mon
  action:
    - service: switch.turn_on
      entity_id: switch.gong
- alias: 'Slack Notification'
  trigger:
    platform: state
    entity_id: light.dali
    to: 'on'
  action:
    - service: notify.slack
      data:
        message: "CIAO from HOME ASSISTANT :smile:, Dali light is ON"
# - alias: 'Dali lights automation'
#   trigger:
#     platform: time
#     # When 'after' is used, you cannot also match on hour, minute, seconds.
#     # Military time format.
#     after: '16:45:00'
#   action:
#     - service: switch.turn_on
#       entity_id: switch.dali
- alias: enOcean to Dali
  trigger:
    platform: event
    event_type: button_pressed
    event_data:
      id: [0xFE,0xFB,0xFE,0x61]
      pushed: 0
  action:
    - service: light.turn_on
      entity_id: light.dali

group: !include groups.yaml


