homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.5155
  longitude: 13.4062
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 32
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

# Example configuration.yaml entry
#arduino:
#  port: /dev/ttyACM0

# Example configuration.yaml entry
#switch:
#  platform: arduino
#  pins:
#    13:
#      name: Light Desk
#      initial: false 
#      negate: false 

# Example configuration.yaml entry
#device_tracker:
#  - platform: bluetooth_le_tracker
#    discovery: enabled
#    track_new_devices: True
#    consider_home: 180
#    interval_seconds: 5

notify:
  - name: slack
    username: HomeAssistant
    platform: slack
    api_key: !secret slackapikey
    default_channel: '@riccardo'
    icon: ":house_with_garden:"

switch:
  - platform: gog 
  - platform: dali

# automation:
# - alias: 'Morning Alignment Gong'
#   trigger:
#     platform: time
#     # When 'after' is used, you cannot also match on hour, minute, seconds.
#     # Military time format.
#     after: '10:00:00'
#   action:
#     - service: switch.turn_on

# switch:
#   platform: dali 

automation:
- alias: '10.00 Daily Alignment Gong'
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    after: '10:00:00'
  condition:
  - condition: time
    weekday:
      - tue
      - wed
      - thu
      - fri
  action:
    - service: switch.turn_on
      entity_id: switch.gog
- alias: '9.00 Monday Alignment Gong'
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    after: '9:00:00'
  condition:
  - condition: time
    weekday:
      - mon
  action:
    - service: switch.turn_on
      entity_id: switch.gog
- alias: 'Slack Notification'
  trigger:
    platform: state
    entity_id: switch.dali
    to: 'on'
  action:
    - service: notify.slack
      data:
        message: "CIAO from HOME ASSISTANT :smile:"

group: !include groups.yaml


